# 告诉Railway使用Nixpacks构建，并明确是Python项目
[build]
builder = "NIXPACKS"
# 明确指定语言为Python，避免Nixpacks识别失败
language = "PYTHON"
# 构建命令：用清华源安装依赖
buildCommand = "pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple"

# 部署配置：指定启动命令
[deploy]
startCommand = "python main.py"
# 可选：设置Python版本
pythonVersion = "3.10.18"